// <auto-generated />
using System;
using ClinicaVeterinaria.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClinicaVeterinaria.Migrations
{
    [DbContext(typeof(ClinicaContext))]
    partial class ClinicaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClinicaVeterinaria.Models.LogErro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataHoraRegistro")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("InnerException")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("StackTrace")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("LogErros");
                });

            modelBuilder.Entity("ClinicaVeterinaria.Models.Paciente", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cor")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("EResultadoTriagem")
                        .HasColumnType("text");

                    b.Property<string>("Especie")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double?>("Idade")
                        .HasColumnType("double precision");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double?>("Peso")
                        .HasColumnType("double precision");

                    b.Property<string>("Raca")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid?>("TutorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TutorId");

                    b.ToTable("Pacientes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("368a4087-3de7-4bc8-921e-aa6a5a9be54a"),
                            Cor = "Preta",
                            EResultadoTriagem = "Odontologia",
                            Especie = "Cachorro",
                            Idade = 4.0,
                            Nome = "Nymeria",
                            Peso = 22.0,
                            Raca = "Pastor Alemão",
                            TutorId = new Guid("ea249baa-c22a-495f-981b-ed6d7c9ea029")
                        },
                        new
                        {
                            Id = new Guid("234eea2a-0348-45b5-99a1-44b20f010e03"),
                            Cor = "Marrom",
                            EResultadoTriagem = "Cardiologia",
                            Especie = "Cachorro",
                            Idade = 7.0,
                            Nome = "Mel",
                            Peso = 10.0,
                            Raca = "Shitzu",
                            TutorId = new Guid("40213770-be5a-4c20-9a3b-31e405378768")
                        });
                });

            modelBuilder.Entity("ClinicaVeterinaria.Models.Tutor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DataNascimento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tutores");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ea249baa-c22a-495f-981b-ed6d7c9ea029"),
                            CPF = "12312332124",
                            DataNascimento = "02/05/2002",
                            Endereco = "Cabedelo",
                            Nome = "Cairo",
                            Telefone = "99999999"
                        },
                        new
                        {
                            Id = new Guid("40213770-be5a-4c20-9a3b-31e405378768"),
                            CPF = "12312332124",
                            DataNascimento = "05/07/2000",
                            Endereco = "JP",
                            Nome = "Rita",
                            Telefone = "99999999"
                        });
                });

            modelBuilder.Entity("ClinicaVeterinaria.Models.Paciente", b =>
                {
                    b.HasOne("ClinicaVeterinaria.Models.Tutor", null)
                        .WithMany("PacienteList")
                        .HasForeignKey("TutorId");
                });

            modelBuilder.Entity("ClinicaVeterinaria.Models.Tutor", b =>
                {
                    b.Navigation("PacienteList");
                });
#pragma warning restore 612, 618
        }
    }
}
