// <auto-generated />
using System;
using ClinicaVeterinaria.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClinicaVeterinaria.Migrations
{
    [DbContext(typeof(ClinicaContext))]
    partial class ClinicaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClinicaVeterinaria.Models.LogErro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataHoraRegistro")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("InnerException")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("StackTrace")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("LogErros");
                });

            modelBuilder.Entity("ClinicaVeterinaria.Models.Paciente", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cor")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("EResultadoTriagem")
                        .HasColumnType("text");

                    b.Property<string>("Especie")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double?>("Idade")
                        .HasColumnType("double precision");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double?>("Peso")
                        .HasColumnType("double precision");

                    b.Property<string>("Raca")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid?>("TutorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TutorId");

                    b.ToTable("Pacientes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("368a4087-3de7-4bc8-921e-aa6a5a9be54a"),
                            Cor = "Preta",
                            EResultadoTriagem = "Odontologia",
                            Especie = "Cachorro",
                            Idade = 4.0,
                            Nome = "Nymeria",
                            Peso = 22.0,
                            Raca = "Pastor Alemão",
                            TutorId = new Guid("ea249baa-c22a-495f-981b-ed6d7c9ea029")
                        },
                        new
                        {
                            Id = new Guid("234eea2a-0348-45b5-99a1-44b20f010e03"),
                            Cor = "Marrom",
                            EResultadoTriagem = "Cardiologia",
                            Especie = "Cachorro",
                            Idade = 7.0,
                            Nome = "Mel",
                            Peso = 10.0,
                            Raca = "Shitzu",
                            TutorId = new Guid("40213770-be5a-4c20-9a3b-31e405378768")
                        },
                        new
                        {
                            Id = new Guid("59045bc1-2b6c-4f5a-a01d-79f5190a28e3"),
                            Cor = "Laranja",
                            EResultadoTriagem = "Cardiologia",
                            Especie = "Peixe",
                            Idade = 30.0,
                            Nome = "Nemo",
                            Peso = 1.0,
                            Raca = "Peixe Palhaço",
                            TutorId = new Guid("ea249baa-c22a-495f-981b-ed6d7c9ea029")
                        },
                        new
                        {
                            Id = new Guid("3abe35e4-ec64-4226-8ec7-f2d4fe942177"),
                            Cor = "Preta e branca",
                            EResultadoTriagem = "Endocrinologia",
                            Especie = "Cachorro",
                            Idade = 4.0,
                            Nome = "Maya",
                            Peso = 10.0,
                            Raca = "Shitzu",
                            TutorId = new Guid("40213770-be5a-4c20-9a3b-31e405378768")
                        },
                        new
                        {
                            Id = new Guid("eaa6291d-849a-471d-bc0b-2be7bcc3c696"),
                            Cor = "Azul",
                            EResultadoTriagem = "Nutrologia",
                            Especie = "Pokemón Tartaruga",
                            Idade = 12.0,
                            Nome = "Giga",
                            Peso = 700.0,
                            Raca = "Blastoise",
                            TutorId = new Guid("40213770-be5a-4c20-9a3b-31e405378768")
                        },
                        new
                        {
                            Id = new Guid("9bac6f15-a352-481c-b06e-3e0d82f18ff4"),
                            Cor = "Verde e branca",
                            EResultadoTriagem = "Oftalmologia",
                            Especie = "Pokemón Gato",
                            Idade = 5.0,
                            Nome = "Snorlax",
                            Peso = 1000.0,
                            Raca = "Snorlax",
                            TutorId = new Guid("ea249baa-c22a-495f-981b-ed6d7c9ea029")
                        },
                        new
                        {
                            Id = new Guid("0628d876-63b3-4b5e-923e-0678941494e5"),
                            Cor = "Laranja",
                            EResultadoTriagem = "Hematologia",
                            Especie = "Dragão",
                            Idade = 3.0,
                            Nome = "Dragaozinho",
                            Peso = 40.0,
                            Raca = "Charmander",
                            TutorId = new Guid("ea249baa-c22a-495f-981b-ed6d7c9ea029")
                        },
                        new
                        {
                            Id = new Guid("2694f3ac-9c20-4612-9179-d888a1a0f696"),
                            Cor = "Laranja",
                            EResultadoTriagem = "Nefrologia",
                            Especie = "Sapo",
                            Idade = 50.0,
                            Nome = "Gamabunta",
                            Peso = 1000.0,
                            Raca = "Sapo gigante",
                            TutorId = new Guid("6abd8cf3-4750-4cac-925f-8eaaea34234e")
                        });
                });

            modelBuilder.Entity("ClinicaVeterinaria.Models.Tutor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DataNascimento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tutores");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ea249baa-c22a-495f-981b-ed6d7c9ea029"),
                            Ativo = true,
                            CPF = "12312332124",
                            DataNascimento = "16/10/1997",
                            Endereco = "Konoha",
                            Nome = "Naruto",
                            Telefone = "99999999"
                        },
                        new
                        {
                            Id = new Guid("40213770-be5a-4c20-9a3b-31e405378768"),
                            Ativo = true,
                            CPF = "12312332124",
                            DataNascimento = "03/05/1990",
                            Endereco = "Grand Line",
                            Nome = "Luffy",
                            Telefone = "99999999"
                        },
                        new
                        {
                            Id = new Guid("6abd8cf3-4750-4cac-925f-8eaaea34234e"),
                            Ativo = false,
                            CPF = "12312332124",
                            DataNascimento = "06/05/1987",
                            Endereco = "Konoha",
                            Nome = "Jiraya",
                            Telefone = "99999999"
                        });
                });

            modelBuilder.Entity("ClinicaVeterinaria.Models.Paciente", b =>
                {
                    b.HasOne("ClinicaVeterinaria.Models.Tutor", null)
                        .WithMany("PacienteList")
                        .HasForeignKey("TutorId");
                });

            modelBuilder.Entity("ClinicaVeterinaria.Models.Tutor", b =>
                {
                    b.Navigation("PacienteList");
                });
#pragma warning restore 612, 618
        }
    }
}
