version: '3.7'
services:
    clinicavetapi:
        image: ${DOCKER_REGISTRY-}clinicaveterinaria2
        build:
            context: ../ClinicaVeterinaria
            dockerfile: ../ClinicaVeterinaria/Dockerfile
        ports:
            - "5000:80"
        depends_on:
            - postgres
    postgres:
        image: postgres
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=clinica-veterinaria
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5438:5432'
        #volumes:
          #- [caminho local]:/var/opt/postgres/data   